/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangSugarAlternativesRouteImport } from './routes/$lang.sugar-alternatives'
import { Route as LangPartnersRouteImport } from './routes/$lang.partners'
import { Route as LangOralCareRouteImport } from './routes/$lang.oral-care'
import { Route as LangImmunityVitaminCRouteImport } from './routes/$lang.immunity-vitamin-c'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCatalogsRouteImport } from './routes/$lang.catalogs'
import { Route as LangBrandsRouteImport } from './routes/$lang.brands'
import { Route as LangBabyCareRouteImport } from './routes/$lang.baby-care'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangBrandsIndexRouteImport } from './routes/$lang.brands.index'
import { Route as LangNewsSlugRouteImport } from './routes/$lang.news.$slug'
import { Route as LangBrandsSlugRouteImport } from './routes/$lang.brands.$slug'
import { Route as LangAdminSeoRouteImport } from './routes/$lang.admin.seo'
import { Route as LangBrandsSlugIndexRouteImport } from './routes/$lang.brands.$slug.index'
import { Route as LangBrandsSlugProductSlugRouteImport } from './routes/$lang.brands.$slug.$productSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSugarAlternativesRoute = LangSugarAlternativesRouteImport.update({
  id: '/sugar-alternatives',
  path: '/sugar-alternatives',
  getParentRoute: () => LangRoute,
} as any)
const LangPartnersRoute = LangPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LangRoute,
} as any)
const LangOralCareRoute = LangOralCareRouteImport.update({
  id: '/oral-care',
  path: '/oral-care',
  getParentRoute: () => LangRoute,
} as any)
const LangImmunityVitaminCRoute = LangImmunityVitaminCRouteImport.update({
  id: '/immunity-vitamin-c',
  path: '/immunity-vitamin-c',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCatalogsRoute = LangCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => LangRoute,
} as any)
const LangBrandsRoute = LangBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => LangRoute,
} as any)
const LangBabyCareRoute = LangBabyCareRouteImport.update({
  id: '/baby-care',
  path: '/baby-care',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangBrandsIndexRoute = LangBrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangBrandsRoute,
} as any)
const LangNewsSlugRoute = LangNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangBrandsSlugRoute = LangBrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangBrandsRoute,
} as any)
const LangAdminSeoRoute = LangAdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => LangRoute,
} as any)
const LangBrandsSlugIndexRoute = LangBrandsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangBrandsSlugRoute,
} as any)
const LangBrandsSlugProductSlugRoute =
  LangBrandsSlugProductSlugRouteImport.update({
    id: '/$productSlug',
    path: '/$productSlug',
    getParentRoute: () => LangBrandsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/baby-care': typeof LangBabyCareRoute
  '/$lang/brands': typeof LangBrandsRouteWithChildren
  '/$lang/catalogs': typeof LangCatalogsRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/immunity-vitamin-c': typeof LangImmunityVitaminCRoute
  '/$lang/oral-care': typeof LangOralCareRoute
  '/$lang/partners': typeof LangPartnersRoute
  '/$lang/sugar-alternatives': typeof LangSugarAlternativesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/seo': typeof LangAdminSeoRoute
  '/$lang/brands/$slug': typeof LangBrandsSlugRouteWithChildren
  '/$lang/news/$slug': typeof LangNewsSlugRoute
  '/$lang/brands/': typeof LangBrandsIndexRoute
  '/$lang/brands/$slug/$productSlug': typeof LangBrandsSlugProductSlugRoute
  '/$lang/brands/$slug/': typeof LangBrandsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/baby-care': typeof LangBabyCareRoute
  '/$lang/catalogs': typeof LangCatalogsRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/immunity-vitamin-c': typeof LangImmunityVitaminCRoute
  '/$lang/oral-care': typeof LangOralCareRoute
  '/$lang/partners': typeof LangPartnersRoute
  '/$lang/sugar-alternatives': typeof LangSugarAlternativesRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/seo': typeof LangAdminSeoRoute
  '/$lang/news/$slug': typeof LangNewsSlugRoute
  '/$lang/brands': typeof LangBrandsIndexRoute
  '/$lang/brands/$slug/$productSlug': typeof LangBrandsSlugProductSlugRoute
  '/$lang/brands/$slug': typeof LangBrandsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/baby-care': typeof LangBabyCareRoute
  '/$lang/brands': typeof LangBrandsRouteWithChildren
  '/$lang/catalogs': typeof LangCatalogsRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/immunity-vitamin-c': typeof LangImmunityVitaminCRoute
  '/$lang/oral-care': typeof LangOralCareRoute
  '/$lang/partners': typeof LangPartnersRoute
  '/$lang/sugar-alternatives': typeof LangSugarAlternativesRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/seo': typeof LangAdminSeoRoute
  '/$lang/brands/$slug': typeof LangBrandsSlugRouteWithChildren
  '/$lang/news/$slug': typeof LangNewsSlugRoute
  '/$lang/brands/': typeof LangBrandsIndexRoute
  '/$lang/brands/$slug/$productSlug': typeof LangBrandsSlugProductSlugRoute
  '/$lang/brands/$slug/': typeof LangBrandsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/baby-care'
    | '/$lang/brands'
    | '/$lang/catalogs'
    | '/$lang/contact'
    | '/$lang/immunity-vitamin-c'
    | '/$lang/oral-care'
    | '/$lang/partners'
    | '/$lang/sugar-alternatives'
    | '/$lang/'
    | '/$lang/admin/seo'
    | '/$lang/brands/$slug'
    | '/$lang/news/$slug'
    | '/$lang/brands/'
    | '/$lang/brands/$slug/$productSlug'
    | '/$lang/brands/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/baby-care'
    | '/$lang/catalogs'
    | '/$lang/contact'
    | '/$lang/immunity-vitamin-c'
    | '/$lang/oral-care'
    | '/$lang/partners'
    | '/$lang/sugar-alternatives'
    | '/$lang'
    | '/$lang/admin/seo'
    | '/$lang/news/$slug'
    | '/$lang/brands'
    | '/$lang/brands/$slug/$productSlug'
    | '/$lang/brands/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/baby-care'
    | '/$lang/brands'
    | '/$lang/catalogs'
    | '/$lang/contact'
    | '/$lang/immunity-vitamin-c'
    | '/$lang/oral-care'
    | '/$lang/partners'
    | '/$lang/sugar-alternatives'
    | '/$lang/'
    | '/$lang/admin/seo'
    | '/$lang/brands/$slug'
    | '/$lang/news/$slug'
    | '/$lang/brands/'
    | '/$lang/brands/$slug/$productSlug'
    | '/$lang/brands/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sugar-alternatives': {
      id: '/$lang/sugar-alternatives'
      path: '/sugar-alternatives'
      fullPath: '/$lang/sugar-alternatives'
      preLoaderRoute: typeof LangSugarAlternativesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/partners': {
      id: '/$lang/partners'
      path: '/partners'
      fullPath: '/$lang/partners'
      preLoaderRoute: typeof LangPartnersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/oral-care': {
      id: '/$lang/oral-care'
      path: '/oral-care'
      fullPath: '/$lang/oral-care'
      preLoaderRoute: typeof LangOralCareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/immunity-vitamin-c': {
      id: '/$lang/immunity-vitamin-c'
      path: '/immunity-vitamin-c'
      fullPath: '/$lang/immunity-vitamin-c'
      preLoaderRoute: typeof LangImmunityVitaminCRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/catalogs': {
      id: '/$lang/catalogs'
      path: '/catalogs'
      fullPath: '/$lang/catalogs'
      preLoaderRoute: typeof LangCatalogsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/brands': {
      id: '/$lang/brands'
      path: '/brands'
      fullPath: '/$lang/brands'
      preLoaderRoute: typeof LangBrandsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/baby-care': {
      id: '/$lang/baby-care'
      path: '/baby-care'
      fullPath: '/$lang/baby-care'
      preLoaderRoute: typeof LangBabyCareRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/brands/': {
      id: '/$lang/brands/'
      path: '/'
      fullPath: '/$lang/brands/'
      preLoaderRoute: typeof LangBrandsIndexRouteImport
      parentRoute: typeof LangBrandsRoute
    }
    '/$lang/news/$slug': {
      id: '/$lang/news/$slug'
      path: '/news/$slug'
      fullPath: '/$lang/news/$slug'
      preLoaderRoute: typeof LangNewsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/brands/$slug': {
      id: '/$lang/brands/$slug'
      path: '/$slug'
      fullPath: '/$lang/brands/$slug'
      preLoaderRoute: typeof LangBrandsSlugRouteImport
      parentRoute: typeof LangBrandsRoute
    }
    '/$lang/admin/seo': {
      id: '/$lang/admin/seo'
      path: '/admin/seo'
      fullPath: '/$lang/admin/seo'
      preLoaderRoute: typeof LangAdminSeoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/brands/$slug/': {
      id: '/$lang/brands/$slug/'
      path: '/'
      fullPath: '/$lang/brands/$slug/'
      preLoaderRoute: typeof LangBrandsSlugIndexRouteImport
      parentRoute: typeof LangBrandsSlugRoute
    }
    '/$lang/brands/$slug/$productSlug': {
      id: '/$lang/brands/$slug/$productSlug'
      path: '/$productSlug'
      fullPath: '/$lang/brands/$slug/$productSlug'
      preLoaderRoute: typeof LangBrandsSlugProductSlugRouteImport
      parentRoute: typeof LangBrandsSlugRoute
    }
  }
}

interface LangBrandsSlugRouteChildren {
  LangBrandsSlugProductSlugRoute: typeof LangBrandsSlugProductSlugRoute
  LangBrandsSlugIndexRoute: typeof LangBrandsSlugIndexRoute
}

const LangBrandsSlugRouteChildren: LangBrandsSlugRouteChildren = {
  LangBrandsSlugProductSlugRoute: LangBrandsSlugProductSlugRoute,
  LangBrandsSlugIndexRoute: LangBrandsSlugIndexRoute,
}

const LangBrandsSlugRouteWithChildren = LangBrandsSlugRoute._addFileChildren(
  LangBrandsSlugRouteChildren,
)

interface LangBrandsRouteChildren {
  LangBrandsSlugRoute: typeof LangBrandsSlugRouteWithChildren
  LangBrandsIndexRoute: typeof LangBrandsIndexRoute
}

const LangBrandsRouteChildren: LangBrandsRouteChildren = {
  LangBrandsSlugRoute: LangBrandsSlugRouteWithChildren,
  LangBrandsIndexRoute: LangBrandsIndexRoute,
}

const LangBrandsRouteWithChildren = LangBrandsRoute._addFileChildren(
  LangBrandsRouteChildren,
)

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBabyCareRoute: typeof LangBabyCareRoute
  LangBrandsRoute: typeof LangBrandsRouteWithChildren
  LangCatalogsRoute: typeof LangCatalogsRoute
  LangContactRoute: typeof LangContactRoute
  LangImmunityVitaminCRoute: typeof LangImmunityVitaminCRoute
  LangOralCareRoute: typeof LangOralCareRoute
  LangPartnersRoute: typeof LangPartnersRoute
  LangSugarAlternativesRoute: typeof LangSugarAlternativesRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAdminSeoRoute: typeof LangAdminSeoRoute
  LangNewsSlugRoute: typeof LangNewsSlugRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBabyCareRoute: LangBabyCareRoute,
  LangBrandsRoute: LangBrandsRouteWithChildren,
  LangCatalogsRoute: LangCatalogsRoute,
  LangContactRoute: LangContactRoute,
  LangImmunityVitaminCRoute: LangImmunityVitaminCRoute,
  LangOralCareRoute: LangOralCareRoute,
  LangPartnersRoute: LangPartnersRoute,
  LangSugarAlternativesRoute: LangSugarAlternativesRoute,
  LangIndexRoute: LangIndexRoute,
  LangAdminSeoRoute: LangAdminSeoRoute,
  LangNewsSlugRoute: LangNewsSlugRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
