/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogsRouteImport } from './routes/catalogs'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as BrandsSlugIndexRouteImport } from './routes/brands.$slug.index'
import { Route as BrandsSlugProductSlugRouteImport } from './routes/brands.$slug.$productSlug'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsRoute = CatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsSlugIndexRoute = BrandsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsSlugRoute,
} as any)
const BrandsSlugProductSlugRoute = BrandsSlugProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => BrandsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/brands/$slug': typeof BrandsSlugRouteWithChildren
  '/brands/': typeof BrandsIndexRoute
  '/brands/$slug/$productSlug': typeof BrandsSlugProductSlugRoute
  '/brands/$slug/': typeof BrandsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/brands': typeof BrandsIndexRoute
  '/brands/$slug/$productSlug': typeof BrandsSlugProductSlugRoute
  '/brands/$slug': typeof BrandsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRouteWithChildren
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/brands/$slug': typeof BrandsSlugRouteWithChildren
  '/brands/': typeof BrandsIndexRoute
  '/brands/$slug/$productSlug': typeof BrandsSlugProductSlugRoute
  '/brands/$slug/': typeof BrandsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/catalogs'
    | '/contact'
    | '/partners'
    | '/brands/$slug'
    | '/brands/'
    | '/brands/$slug/$productSlug'
    | '/brands/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalogs'
    | '/contact'
    | '/partners'
    | '/brands'
    | '/brands/$slug/$productSlug'
    | '/brands/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/catalogs'
    | '/contact'
    | '/partners'
    | '/brands/$slug'
    | '/brands/'
    | '/brands/$slug/$productSlug'
    | '/brands/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  CatalogsRoute: typeof CatalogsRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs': {
      id: '/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof CatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$slug/': {
      id: '/brands/$slug/'
      path: '/'
      fullPath: '/brands/$slug/'
      preLoaderRoute: typeof BrandsSlugIndexRouteImport
      parentRoute: typeof BrandsSlugRoute
    }
    '/brands/$slug/$productSlug': {
      id: '/brands/$slug/$productSlug'
      path: '/$productSlug'
      fullPath: '/brands/$slug/$productSlug'
      preLoaderRoute: typeof BrandsSlugProductSlugRouteImport
      parentRoute: typeof BrandsSlugRoute
    }
  }
}

interface BrandsSlugRouteChildren {
  BrandsSlugProductSlugRoute: typeof BrandsSlugProductSlugRoute
  BrandsSlugIndexRoute: typeof BrandsSlugIndexRoute
}

const BrandsSlugRouteChildren: BrandsSlugRouteChildren = {
  BrandsSlugProductSlugRoute: BrandsSlugProductSlugRoute,
  BrandsSlugIndexRoute: BrandsSlugIndexRoute,
}

const BrandsSlugRouteWithChildren = BrandsSlugRoute._addFileChildren(
  BrandsSlugRouteChildren,
)

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRouteWithChildren
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRouteWithChildren,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRouteWithChildren,
  CatalogsRoute: CatalogsRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
